[package]
name = "tisdb"
version = "0.1.0-dev.1"
edition = "2024"
rust-version = "1.96.0"
resolver = "3"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fslock = "0.2.1"
rkyv = "0.8.18"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
ulid = "3.0.0"
wasm-bindgen = { version = "0.2.128", optional = true }

[features]
wasm-bindgen = ["dep:wasm-bindgen"]

